%TERMINALS%
(
)
{
}
COMMA
$
TYPE
VARNAME
FUNCTION
VOID
%END%

%GRAMMER%

S=PROGRAM$
PROGRAM=PROGRAM FUNCTION_STMT
PROGRAM=FUNCTION_STMT

FUNCTION_STMT=RETURN_TYPE FUNCTION_DECL BODY
RETURN_TYPE=VOID
RETURN_TYPE=TYPE
BODY={}
FUNCTION_DECL= FUNCTION VARNAME (FUNCTION_PARAM)
FUNCTION_PARAM=FUNCTION_PARAM COMMA FUNCTION_PARAM_TERM
FUNCTION_PARAM=FUNCTION_PARAM_TERM
FUNCTION_PARAM_TERM=TYPE VARNAME
FUNCTION_PARAM_TERM=~

%END%